[package]
name = "bkmazefe/econ-engine"
version = "0.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Testez = "roblox/testez@0.4.1"
Promise = "evaera/promise@4.0.0"
ProfileService = "nidoxs/profileservice@1.0.0"